---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kiran007anil/pcf-docker
    tag: final

inputs:
  - name: bbr-pipeline-tasks-repo
outputs:
  - name: om-installation

run:
  path: /bin/sh
  args:
  - -c
  - |
    cd bbr-pipeline-tasks-repo/tasks/export-om-installation/
    chmod +x task.sh
    ./task.sh

params:
  SKIP_SSL_VALIDATION: false
  OPSMAN_URL:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
