---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kiran007anil/pcf-docker
    tag: final

inputs:
  - name: bbr-pipeline-tasks-repo
  - name: binary
outputs:
  - name: director-backup-artifact

params:
  SKIP_SSL_VALIDATION: false
  OPSMAN_URL:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:

run:
  path: /bin/sh
  args:
  - -c
  - |
    cd bbr-pipeline-tasks-repo/tasks/bbr-backup-director/
    chmod +x task.sh
    ./task.sh
